# Generated by Django 5.1.13 on 2025-12-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateconfig',
            name='price_per_fat_unit',
        ),
        migrations.AddField(
            model_name='milkentry',
            name='milk_type',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Buffalo', 'Buffalo')], default='Cow', max_length=10),
        ),
        migrations.AddField(
            model_name='rateconfig',
            name='price_buffalo_fat',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Buffalo Rate'),
        ),
        migrations.AddField(
            model_name='rateconfig',
            name='price_cow_fat',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Cow Rate'),
        ),
    ]
