# Generated by Django 6.0 on 2026-02-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_rateconfig_price_per_fat_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_farmer',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
