# Generated by Django 6.0 on 2026-02-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_is_farmer_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_farmer',
            field=models.BooleanField(default=False),
        ),
    ]
