# Generated by Django 6.0 on 2026-02-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkentry',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
